# For this server to take effect run the following commands
# sudo cp nginx.conf /etc/nginx/conf.d/dmj_web.conf
# sudo nginx -t
# sudo nginx -s reload
server {
        listen 80;
        listen 443 ssl;
        server_name localhost danbotlab.local danbotlab *.danbotlab.local *.danbotlab;
        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        location / {
            root /home/danbot/dev/dmj_web/;
        }
}
server {
        listen 80;
        listen 443 ssl;
        server_name danielmarkjones.com *.danielmarkjones.com;
        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        location / {
            root /opt/dmj_web/;
        }
}