---
- hosts: dmj
  become: true
  tasks:
    - yum:
        name: nginx
    - copy:
        src: dmj.conf
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
        mode: '0644'
      notify: reload nginx
    - systemd:
        enabled: true
        daemon-reload: true
        name: nginx
        state: started
    - copy: 
        src: ../dmj_web
        dest: /data/
        owner: nginx
        group: nginx
        mode: '644'
  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: restarted
